[2024-05-22 02:20:21,196] {taskinstance.py:1032} INFO - Dependencies all met for <TaskInstance: purpleair_api_dag.fetch_data scheduled__2024-05-21T04:00:00+00:00 [queued]>
[2024-05-22 02:20:21,312] {taskinstance.py:1032} INFO - Dependencies all met for <TaskInstance: purpleair_api_dag.fetch_data scheduled__2024-05-21T04:00:00+00:00 [queued]>
[2024-05-22 02:20:21,318] {taskinstance.py:1238} INFO - 
--------------------------------------------------------------------------------
[2024-05-22 02:20:21,319] {taskinstance.py:1239} INFO - Starting attempt 1 of 2
[2024-05-22 02:20:21,320] {taskinstance.py:1240} INFO - 
--------------------------------------------------------------------------------
[2024-05-22 02:20:21,464] {taskinstance.py:1259} INFO - Executing <Task(PythonOperator): fetch_data> on 2024-05-21 04:00:00+00:00
[2024-05-22 02:20:21,544] {standard_task_runner.py:52} INFO - Started process 2348 to run task
[2024-05-22 02:20:21,562] {standard_task_runner.py:76} INFO - Running: ['***', 'tasks', 'run', 'purpleair_api_dag', 'fetch_data', 'scheduled__2024-05-21T04:00:00+00:00', '--job-id', '5', '--raw', '--subdir', 'DAGS_FOLDER/data_ingestion.py', '--cfg-path', '/tmp/tmplso2xqd1', '--error-file', '/tmp/tmpic9pxb1a']
[2024-05-22 02:20:21,638] {standard_task_runner.py:77} INFO - Job 5: Subtask fetch_data
[2024-05-22 02:20:22,169] {logging_mixin.py:109} INFO - Running <TaskInstance: purpleair_api_dag.fetch_data scheduled__2024-05-21T04:00:00+00:00 [running]> on host 8fe6997c1526
[2024-05-22 02:20:22,504] {taskinstance.py:1426} INFO - Exporting the following env vars:
AIRFLOW_CTX_DAG_OWNER=***
AIRFLOW_CTX_DAG_ID=purpleair_api_dag
AIRFLOW_CTX_TASK_ID=fetch_data
AIRFLOW_CTX_EXECUTION_DATE=2024-05-21T04:00:00+00:00
AIRFLOW_CTX_DAG_RUN_ID=scheduled__2024-05-21T04:00:00+00:00
[2024-05-22 02:20:22,908] {logging_mixin.py:109} INFO - Failed to retrieve data: 403
[2024-05-22 02:20:22,909] {python.py:175} INFO - Done. Returned value was: None
[2024-05-22 02:20:22,997] {taskinstance.py:1277} INFO - Marking task as SUCCESS. dag_id=purpleair_api_dag, task_id=fetch_data, execution_date=20240521T040000, start_date=20240522T022021, end_date=20240522T022022
[2024-05-22 02:20:23,239] {local_task_job.py:154} INFO - Task exited with return code 0
[2024-05-22 02:20:23,391] {local_task_job.py:264} INFO - 0 downstream tasks scheduled from follow-on schedule check
[2024-05-22 04:14:08,017] {taskinstance.py:1032} INFO - Dependencies all met for <TaskInstance: purpleair_api_dag.fetch_data scheduled__2024-05-21T04:00:00+00:00 [queued]>
[2024-05-22 04:14:08,143] {taskinstance.py:1032} INFO - Dependencies all met for <TaskInstance: purpleair_api_dag.fetch_data scheduled__2024-05-21T04:00:00+00:00 [queued]>
[2024-05-22 04:14:08,152] {taskinstance.py:1238} INFO - 
--------------------------------------------------------------------------------
[2024-05-22 04:14:08,160] {taskinstance.py:1239} INFO - Starting attempt 1 of 2
[2024-05-22 04:14:08,161] {taskinstance.py:1240} INFO - 
--------------------------------------------------------------------------------
[2024-05-22 04:14:08,293] {taskinstance.py:1259} INFO - Executing <Task(PythonOperator): fetch_data> on 2024-05-21 04:00:00+00:00
[2024-05-22 04:14:08,326] {standard_task_runner.py:52} INFO - Started process 130 to run task
[2024-05-22 04:14:08,387] {standard_task_runner.py:76} INFO - Running: ['***', 'tasks', 'run', 'purpleair_api_dag', 'fetch_data', 'scheduled__2024-05-21T04:00:00+00:00', '--job-id', '2', '--raw', '--subdir', 'DAGS_FOLDER/data_ingestion.py', '--cfg-path', '/tmp/tmpna8tnw3a', '--error-file', '/tmp/tmpva4iphar']
[2024-05-22 04:14:08,496] {standard_task_runner.py:77} INFO - Job 2: Subtask fetch_data
[2024-05-22 04:14:09,058] {logging_mixin.py:109} INFO - Running <TaskInstance: purpleair_api_dag.fetch_data scheduled__2024-05-21T04:00:00+00:00 [running]> on host 3419eee920a5
[2024-05-22 04:14:09,509] {taskinstance.py:1426} INFO - Exporting the following env vars:
AIRFLOW_CTX_DAG_OWNER=***
AIRFLOW_CTX_DAG_ID=purpleair_api_dag
AIRFLOW_CTX_TASK_ID=fetch_data
AIRFLOW_CTX_EXECUTION_DATE=2024-05-21T04:00:00+00:00
AIRFLOW_CTX_DAG_RUN_ID=scheduled__2024-05-21T04:00:00+00:00
[2024-05-22 04:14:09,512] {taskinstance.py:1700} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.6/site-packages/airflow/models/taskinstance.py", line 1329, in _run_raw_task
    self._execute_task_with_callbacks(context)
  File "/home/airflow/.local/lib/python3.6/site-packages/airflow/models/taskinstance.py", line 1455, in _execute_task_with_callbacks
    result = self._execute_task(context, self.task)
  File "/home/airflow/.local/lib/python3.6/site-packages/airflow/models/taskinstance.py", line 1511, in _execute_task
    result = execute_callable(context=context)
  File "/home/airflow/.local/lib/python3.6/site-packages/airflow/operators/python.py", line 174, in execute
    return_value = self.execute_callable()
  File "/home/airflow/.local/lib/python3.6/site-packages/airflow/operators/python.py", line 185, in execute_callable
    return self.python_callable(*self.op_args, **self.op_kwargs)
  File "/opt/airflow/dags/data_ingestion.py", line 67, in api_url
    print(f" url is {url}")
NameError: name 'url' is not defined
[2024-05-22 04:14:09,617] {taskinstance.py:1277} INFO - Marking task as UP_FOR_RETRY. dag_id=purpleair_api_dag, task_id=fetch_data, execution_date=20240521T040000, start_date=20240522T041408, end_date=20240522T041409
[2024-05-22 04:14:09,749] {standard_task_runner.py:92} ERROR - Failed to execute job 2 for task fetch_data
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.6/site-packages/airflow/task/task_runner/standard_task_runner.py", line 85, in _start_by_fork
    args.func(args, dag=self.dag)
  File "/home/airflow/.local/lib/python3.6/site-packages/airflow/cli/cli_parser.py", line 48, in command
    return func(*args, **kwargs)
  File "/home/airflow/.local/lib/python3.6/site-packages/airflow/utils/cli.py", line 92, in wrapper
    return f(*args, **kwargs)
  File "/home/airflow/.local/lib/python3.6/site-packages/airflow/cli/commands/task_command.py", line 298, in task_run
    _run_task_by_selected_method(args, dag, ti)
  File "/home/airflow/.local/lib/python3.6/site-packages/airflow/cli/commands/task_command.py", line 107, in _run_task_by_selected_method
    _run_raw_task(args, ti)
  File "/home/airflow/.local/lib/python3.6/site-packages/airflow/cli/commands/task_command.py", line 184, in _run_raw_task
    error_file=args.error_file,
  File "/home/airflow/.local/lib/python3.6/site-packages/airflow/utils/session.py", line 70, in wrapper
    return func(*args, session=session, **kwargs)
  File "/home/airflow/.local/lib/python3.6/site-packages/airflow/models/taskinstance.py", line 1329, in _run_raw_task
    self._execute_task_with_callbacks(context)
  File "/home/airflow/.local/lib/python3.6/site-packages/airflow/models/taskinstance.py", line 1455, in _execute_task_with_callbacks
    result = self._execute_task(context, self.task)
  File "/home/airflow/.local/lib/python3.6/site-packages/airflow/models/taskinstance.py", line 1511, in _execute_task
    result = execute_callable(context=context)
  File "/home/airflow/.local/lib/python3.6/site-packages/airflow/operators/python.py", line 174, in execute
    return_value = self.execute_callable()
  File "/home/airflow/.local/lib/python3.6/site-packages/airflow/operators/python.py", line 185, in execute_callable
    return self.python_callable(*self.op_args, **self.op_kwargs)
  File "/opt/airflow/dags/data_ingestion.py", line 67, in api_url
    print(f" url is {url}")
NameError: name 'url' is not defined
[2024-05-22 04:14:09,832] {local_task_job.py:154} INFO - Task exited with return code 1
[2024-05-22 04:14:10,039] {local_task_job.py:264} INFO - 0 downstream tasks scheduled from follow-on schedule check
[2024-05-22 04:17:35,970] {taskinstance.py:1032} INFO - Dependencies all met for <TaskInstance: purpleair_api_dag.fetch_data scheduled__2024-05-21T04:00:00+00:00 [queued]>
[2024-05-22 04:17:36,096] {taskinstance.py:1032} INFO - Dependencies all met for <TaskInstance: purpleair_api_dag.fetch_data scheduled__2024-05-21T04:00:00+00:00 [queued]>
[2024-05-22 04:17:36,097] {taskinstance.py:1238} INFO - 
--------------------------------------------------------------------------------
[2024-05-22 04:17:36,097] {taskinstance.py:1239} INFO - Starting attempt 1 of 2
[2024-05-22 04:17:36,097] {taskinstance.py:1240} INFO - 
--------------------------------------------------------------------------------
[2024-05-22 04:17:36,201] {taskinstance.py:1259} INFO - Executing <Task(PythonOperator): fetch_data> on 2024-05-21 04:00:00+00:00
[2024-05-22 04:17:36,233] {standard_task_runner.py:52} INFO - Started process 329 to run task
[2024-05-22 04:17:36,357] {standard_task_runner.py:76} INFO - Running: ['***', 'tasks', 'run', 'purpleair_api_dag', 'fetch_data', 'scheduled__2024-05-21T04:00:00+00:00', '--job-id', '25', '--raw', '--subdir', 'DAGS_FOLDER/data_ingestion.py', '--cfg-path', '/tmp/tmplzuv6vvo', '--error-file', '/tmp/tmp_2gajvzg']
[2024-05-22 04:17:36,490] {standard_task_runner.py:77} INFO - Job 25: Subtask fetch_data
[2024-05-22 04:17:36,959] {logging_mixin.py:109} INFO - Running <TaskInstance: purpleair_api_dag.fetch_data scheduled__2024-05-21T04:00:00+00:00 [running]> on host 3419eee920a5
[2024-05-22 04:17:37,548] {taskinstance.py:1426} INFO - Exporting the following env vars:
AIRFLOW_CTX_DAG_OWNER=***
AIRFLOW_CTX_DAG_ID=purpleair_api_dag
AIRFLOW_CTX_TASK_ID=fetch_data
AIRFLOW_CTX_EXECUTION_DATE=2024-05-21T04:00:00+00:00
AIRFLOW_CTX_DAG_RUN_ID=scheduled__2024-05-21T04:00:00+00:00
[2024-05-22 04:17:37,552] {logging_mixin.py:109} INFO -  api is None
[2024-05-22 04:17:37,557] {logging_mixin.py:109} INFO - Full URL: https://api.purpleair.com/v1/sensors?fields=latitude%2Clongitude%2Chumidity%2Cpm2.5_60minute%2Clast_seen&location_type=0&max_age=300
[2024-05-22 04:17:37,557] {logging_mixin.py:109} INFO - Headers: {'X-API-Key': 'None'}
[2024-05-22 04:17:37,870] {logging_mixin.py:109} INFO - Status Code: 403
[2024-05-22 04:17:37,871] {logging_mixin.py:109} INFO - Response Content: {
  "api_version" : "V1.0.13-0.0.56",
  "time_stamp" : 1716351457,
  "error" : "ApiKeyInvalidError",
  "description" : "The provided api_key was not valid."
}
[2024-05-22 04:17:38,043] {logging_mixin.py:109} INFO - Failed to retrieve data: 403
[2024-05-22 04:17:38,045] {python.py:175} INFO - Done. Returned value was: None
[2024-05-22 04:17:38,174] {taskinstance.py:1277} INFO - Marking task as SUCCESS. dag_id=purpleair_api_dag, task_id=fetch_data, execution_date=20240521T040000, start_date=20240522T041736, end_date=20240522T041738
[2024-05-22 04:17:38,332] {local_task_job.py:154} INFO - Task exited with return code 0
[2024-05-22 04:17:38,536] {local_task_job.py:264} INFO - 0 downstream tasks scheduled from follow-on schedule check
